name: dockerpgvector
services:
  postgres:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pgvector-db
    environment:
      POSTGRES_USER: vectordb
      POSTGRES_PASSWORD: vectorpass
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vectordb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
